"""Create and push a sample 1000m pool swim workout to Garmin Connect, to sanity-check the pipeline.

Structure: 200m choice warmup, 6 x 100m free with lap-button rest, 200m choice cooldown.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

from swim_plan.client import get_client
from swim_plan.swim_workout import build_swim_workout, cooldown_step, swim_repeat, warmup_step

load_dotenv()


def main() -> None:
    steps = [
        warmup_step(200, step_order=1),
        swim_repeat(6, 100, step_order=2, stroke="free", rest_between=True),
        cooldown_step(200, step_order=5),
    ]
    workout = build_swim_workout(
        name="Test Swim - 1000m",
        steps=steps,
        pool_length_meters=25,
        description="Generated by swim-plan: 200 warmup, 6x100 free, 200 cooldown.",
    )

    client = get_client()
    print("Uploading workout...")
    result = client.upload_swimming_workout(workout)
    workout_id = result.get("workoutId") or result.get("id")
    print(f"Uploaded workout id={workout_id}: {result.get('workoutName')}")

    print("Pushing to your last-used device...")
    push_result = client.push_workout_to_device(workout_id=workout_id)
    print("Push result:", push_result)


if __name__ == "__main__":
    main()
